# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lectures at Lunch
email: lecturesatlunch@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  At Lectures at Lunch, we believe in the power of community, diversity, and the joy of learning. Whether you’re working from home, a stay-at-home parent, a student, or simply seeking new experiences, our free online lecture series is designed to bring women together from all walks of life to share knowledge, inspire each other, and forge meaningful connections. Our live sessions offer real-time interaction, allowing for engaging discussions and the opportunity to ask questions. Join us every week for a 20-minute presentation followed by a 20-minute discussion, and become part of a vibrant, inclusive, and judgement-free community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: lecturesatlunch

# Build settings
theme: jekyll-theme-minimal
#remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  #- jekyll-remote-theme

nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Past Lectures"
    url: /past-lectures/
  - title: "FAQ"
    url: /faq/

future: true
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
